# Generated by Django 3.0.4 on 2020-03-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_twilio_worker_sid"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="first_name",),
        migrations.RemoveField(model_name="user", name="last_name",),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Name"),
        ),
    ]
